app/Views/checkout.php
app/Views/index.php
app/Views/products.php
public/assets/css/custom.css

select option checkout , products featured

select option checkout , products featured

---

app/Views/checkout.php
app/Views/myaccount.php
public/assets/css/custom.css

input issue fix ,

---

app/Views/products.php
public/assets/css/custom.css
public/assets/css/style.css

product wishlist ui change

---

app/Controllers/Home.php
app/Views/index.php
public/assets/css/custom.css
public/assets/css/style.css

added best selling products

---

app/Views/components/head.php
app/Views/index.php
public/assets/css/custom.css
public/assets/css/style.css

fontchange, featured products , best seller ui update

fontchange, featured products , best seller ui update

---

app/Views/components/footer.php
app/Views/index.php
app/Views/partials/common_cart_modal.php
app/Views/products.php
public/assets/css/custom.css
public/assets/css/style.css

cart modal ui update

---

app/Controllers/admin/SubmenuController.php
app/Models/admin/SubmenuModel.php
app/Views/admin/sub_menu.php
public/admin/custom/js/submenu.js

added submenu - gst - admin panel

added submenu - gst - admin panel

---

app/Views/cart.php
app/Views/components/header.php

header ui fix and empty cart ui

header ui fix and empty cart ui

---

app/Views/myaccount.php
public/assets/css/custom.css

my account - orders

---

app/Views/index.php
app/Views/productsView.php

top to botton , product view space issue

top to botton , product view space issue

---

public/assets/js/main.js

main js - header change

---

app/Views/myaccount.php
app/Views/products.php
public/assets/css/custom.css

my orders- no orders found

---

app/Views/checkout.php

checkout ui updated

---

app/Views/components/footer.php
app/Views/productsView.php

contact - whatsapp issue fix

---

app/Config/Routes.php
app/Controllers/Home.php
app/Views/cart.php
app/Views/checkout.php
app/Views/components/footer.php
app/Views/components/header.php
app/Views/index.php
app/Views/products.php
custom/js/checkout.js
custom/js/commoncart.js
public/assets/css/custom.css
public/assets/css/style.css

feedbacks - sort , checkout , ui updated

feedbacks - sort , checkout , ui updated

---

app/Controllers/Home.php
app/Views/index.php
public/assets/css/custom.css

best seller - price and status

best seller - price and status

---

app/Views/orderTracking.php
custom/js/address.js
public/assets/css/custom.css

return products ui

---

app/Views/components/footer.php
app/Views/components/header.php

global search icon and base url

global search icon and base url

---

app/Controllers/Home.php

Order by out of stock - filtered data

Order by out of stock - filtered data

---

app/Views/cart.php
app/Views/checkout.php
app/Views/components/footer.php
app/Views/components/header.php
app/Views/index.php
app/Views/productCategories.php
app/Views/products.php
app/Views/productsView.php
public/assets/css/custom.css
public/assets/css/style.css

responsive ui fix

---

app/Views/cart.php
app/Views/myaccount.php
custom/js/commoncart.js
public/assets/css/custom.css

cart resposive

---

public/assets/css/custom.css

cart - border bottom remove in responsive

cart - border bottom remove in responsive

---

app/Views/failed.php
app/Views/success.php
public/assets/css/custom.css

payment success and payment failed ui

payment success and payment failed ui
